var ingredientList = [
"Acid Malt",
"Amber Dry",
"Amber Liquid",
"Amber Malt",
"Aromatic Malt",
"Barley Hulls",
"Barley, Flaked",
"Barley, Raw",
"Barley, Torrefied",
"Biscuit Malt",
"Black (Patent) Malt",
"Black Barley (Stout)",
"Brown Malt",
"Brown Sugar, Dark",
"Brown Sugar, Light",
"Brumalt",
"Candi Sugar, Amber",
"Candi Sugar, Clear",
"Candi Sugar, Dark",
"Cane (Beet) Sugar",
"Cara-Pils/Dextrine",
"Caraamber",
"Carafoam",
"Caramel/Crystal Malt",
"Caramunich Malt",
"Carared",
"Caravienne Malt",
"Chocolate Malt",
"Corn Sugar (Dextrose)",
"Corn Syrup",
"Corn, Flaked",
"Dark Dry Extract",
"Dark Liquid Extract",
"Dememera Sugar",
"Extra Light Dry Extract",
"Grits",
"Honey",
"Invert Sugar",
"Light Dry Extract",
"Maple Syrup",
"Melanoiden Malt",
"Mild Malt",
"Milk Sugar (Lactose)",
"Molasses",
"Munich Malt",
"Oats, Flaked",
"Oats, Malted",
"Pale Liquid Extract",
"Pale Malt (2 Row)",
"Pale Malt (6 Row)",
"Peat Smoked Malt",
"Pilsner (2 Row)",
"Pilsner Liquid",
"Rice Extract Syrup",
"Rice Hulls",
"Rice, Flaked",
"Roasted Barley",
"Rye Malt",
"Rye, Flaked",
"Smoked Malt",
"Special B Malt",
"Special Roast",
"Sugar, Table (Sucrose)",
"Toasted Malt",
"Turbinado",
"Victory Malt",
"Vienna Malt",
"Wheat Dry Extract",
"Wheat Liquid Extract",
"Wheat Malt, Bel",
"Wheat Malt, Dark",
"Wheat Malt, Ger",
"Wheat, Flaked",
"Wheat, Roasted",
"Wheat, Torrified",
"White Wheat Malt",
"Admiral Hops",
"Ahtanum Hops",
"Amarillo Gold Hops",
"Aquila Hops",
"Banner Hops",
"Bramling Cross Hops",
"Brewers Gold Hops",
"Bullion Hops",
"Cascade Hops",
"Centennial Hops",
"Challenger Hops",
"Chinook Hops",
"Cluster Hops",
"Columbia Hops",
"Columbus (Tomahawk) Hops",
"Comet Hops",
"Crystal Hops",
"Eroica Hops",
"First Gold Hops",
"Fuggles Hops",
"Galena Hops",
"Glacier Hops",
"Goldings, B. C. Hops",
"Goldings, East Kent (EK) Hops",
"Green Bullet Hops",
"Hallertauer Hops",
"Hallertauer, Hersbrucker Hops",
"Hallertauer, Mittelfrueh Hops",
"Hallertauer, New Zealand Hops",
"Herald Hops",
"Horizon Hops",
"Liberty Hops",
"Lublin Hops",
"Magnum Hops",
"Mt. Hood Hops",
"Northdown Hops",
"Northern Brewer Hops",
"Nugget Hops",
"Orion Hops",
"Pacific Hops",
"Pearle Hops",
"Phoenix Hops",
"Pilgrim Hops",
"Pioneer Hops",
"Pride of Ringwood Hops",
"Progress Hops",
"Saaz Hops",
"Santiam Hops",
"Select Spalt Hops",
"Southern Cross Hops",
"Spalter Hops",
"Sterling Hops",
"Sticklebract Hops",
"Strisselspalt Hops",
"Styrian Goldings Hops",
"Sun Hops",
"Super Alpha Hops",
"Target Hops",
"Tettnang Hops",
"Tradition Hops",
"Ultra Hops",
"Vanguard Hops",
"Warrior Hops",
"Whitbread Golding Var (WGV) Hops",
"Willamette Hops",
"Zeus Hops",
"Water",
"Cooper Ale",
"Doric Ale",
"Edme Ale Yeast",
"London",
"Manchester",
"Munton Fison Ale",
"Nottingham",
"Nottingham Yeast",
"Pasteur Champagne",
"Red Star Ale",
"Special Ale	Glenbrew",
"Windsor Yeast",
"German Ale",
"American Wheat Ale",
"British Cask Ale",
"London Ale",
"American Ale",
"Irish Ale",
"Wyeast Ale Blend",
"British Ale",
"Whitbread Ale",
"Ringwood Ale",
"Belgian Ale",
"American Ale II",
"GF All American Ale",
"Thames Valley Ale",
"London Ale III",
"Northwest Ale",
"British Ale II",
"European Ale",
"Belgian Strong Ale",
"Scottish Ale",
"Belgian Abbey II",
"London ESB Ale",
"Budvar Lager",
"Urquell Lager",
"Pilsen Lager",
"American Lager",
"Danish Lager",
"California Lager",
"Bohemian Lager",
"Wyeast Lager Blend",
"Bavarian Lager",
"European Lager II",
"North American Lager",
"Czech Pilsner Lager",
"Munich Lager",
"Kolsch Yeast",
"Bavarian Wheat Yeast",
"Weihenstephan Weizen",
"Brettanomyces Bruxellensis",
"Belgian Lambic Blend",
"German Wheat",
"Forbidden Fruit",
"Belgian Ardennes",
"Bavarian Wheat",
"Belgian Saison",
"Roselare Belgian Blend",
"Trappist High Gravity",
"Belgian Wheat Yeast",
"Belgian Witbier",
"Lactobacillus Delbrueckii",
"Pediococcus Cerevisiae",
"Lalvin 71B-1122",
"American Microbrewery Ale #1",
"American Microbrewery Ale #2",
"Noth-Eastern Micro Ale",
"British Microbrewery Ale",
"British Pale Ale #1",
"British Pale Ale #2",
"British Real Ale",
"British Draft Ale",
"Classic British Ale",
"Irish Dry Stout",
"Canadian Ale",
"Belgian Ale #1",
"Belgian Ale #2",
"Belgian Ale #3",
"Saison",
"Kolsch",
"Old German Ale",
"Original Pilsner",
"American Megabrewery",
"American Microbrewery Lager",
"Old Bavarian Lager",
"Northern German Lager",
"East European Lager",
"California Esteem",
"Belgian Wheat",
"German Wheat",
"German Weiss",
"American White Ale",
"Brettanomyces Lambicus",
"Pediococcus Damnosus",
"Lalvin D-47",
"Lalvin EC-1118",
"SafAle German Ale",
"Lalvin - K1V-1116",
"Lalvin RC 212 (Bourgovin)",
"SafAle English Ale",
"SafLager German Lager",
"SafLager West European Lager",
"SafBrew Ale",
"SafBrew Specialty Ale",
"California Ale",
"English Ale",
"German Ale II",
"Irish Ale",
"British Ale",
"Bedford British Ale",
"Dry English Ale",
"East Coast Ale",
"Australian Ale Yeast",
"European Ale",
"London Ale",
"Essex Ale Yeast",
"Burton Ale",
"Southwold Ale",
"Premium Bitter Ale",
"Edinburgh Ale",
"German Ale/Kolsch",
"Klassic Ale Yeast",
"Dusseldorf Alt Yeast",
"Nottingham Ale Yeast",
"Pacific Ale",
"California Ale V",
"Super High Gravity Ale",
"Hefeweizen Ale",
"American Hefeweizen Ale",
"Bavarian Weizen Yeast",
"Hefeweizen IV Ale",
"Belgian Wit Ale",
"Belgian Wit II",
"Trappist Ale",
"Bastogne Belgian Ale",
"Abbey Ale",
"Belgian Ale",
"Belgian Saison I Ale",
"Belgian Golden Ale",
"Belgian Style Ale Yeast Blend",
"Champagne Yeast",
"Sweet Mead/Wine",
"Steinberg-Geisenheim Wine",
"Sweet Mead/Wine",
"English Cider Yeast",
"Pilsner Lager",
"Czech Budejovice Lager",
"San Francisco Lager",
"Octoberfest/Marzen Lager",
"German Lager",
"German Bock Lager",
"Southern German Lager",
"American Lager",
"Cry Havoc",
"Zurich Lager",
"Old Bavarian Lager",
"Mexican Lager"
];