var ingredientList = [
"Acid Malt",
"Amber Dry",
"Amber Liquid",
"Amber Malt",
"Aromatic Malt",
"Barley Hulls",
"Barley, Flaked",
"Barley, Raw",
"Barley, Torrefied",
"Biscuit Malt",
"Black (Patent) Malt",
"Black Barley (Stout)",
"Brown Malt",
"Brown Sugar, Dark",
"Brown Sugar, Light",
"Brumalt",
"Candi Sugar, Amber",
"Candi Sugar, Clear",
"Candi Sugar, Dark",
"Cane (Beet) Sugar",
"Cara-Pils/Dextrine",
"Caraamber",
"Carafoam",
"Caramel/Crystal Malt",
"Caramunich Malt",
"Carared",
"Caravienne Malt",
"Chocolate Malt",
"Corn Sugar (Dextrose)",
"Corn Syrup",
"Corn, Flaked",
"Dark Dry Extract",
"Dark Liquid Extract",
"Dememera Sugar",
"Extra Light Dry Extract",
"Grits",
"Honey",
"Invert Sugar",
"Light Dry Extract",
"Maple Syrup",
"Melanoiden Malt",
"Mild Malt",
"Milk Sugar (Lactose)",
"Molasses",
"Munich Malt",
"Oats, Flaked",
"Oats, Malted",
"Pale Liquid Extract",
"Pale Malt (2 Row)",
"Pale Malt (6 Row)",
"Peat Smoked Malt",
"Pilsner (2 Row)",
"Pilsner Liquid",
"Rice Extract Syrup",
"Rice Hulls",
"Rice, Flaked",
"Roasted Barley",
"Rye Malt",
"Rye, Flaked",
"Smoked Malt",
"Special B Malt",
"Special Roast",
"Sugar, Table (Sucrose)",
"Toasted Malt",
"Turbinado",
"Victory Malt",
"Vienna Malt",
"Wheat Dry Extract",
"Wheat Liquid Extract",
"Wheat Malt, Bel",
"Wheat Malt, Dark",
"Wheat Malt, Ger",
"Wheat, Flaked",
"Wheat, Roasted",
"Wheat, Torrified",
"White Wheat Malt",
"Admiral Hops",
"Ahtanum Hops",
"Amarillo Gold Hops",
"Aquila Hops",
"Banner Hops",
"Bramling Cross Hops",
"Brewers Gold Hops",
"Bullion Hops",
"Cascade Hops",
"Centennial Hops",
"Challenger Hops",
"Chinook Hops",
"Cluster Hops",
"Columbia Hops",
"Columbus (Tomahawk) Hops",
"Comet Hops",
"Crystal Hops",
"Eroica Hops",
"First Gold Hops",
"Fuggles Hops",
"Galena Hops",
"Glacier Hops",
"Goldings, B. C. Hops",
"Goldings, East Kent (EK) Hops",
"Green Bullet Hops",
"Hallertauer Hops",
"Hallertauer, Hersbrucker Hops",
"Hallertauer, Mittelfrueh Hops",
"Hallertauer, New Zealand Hops",
"Herald Hops",
"Horizon Hops",
"Liberty Hops",
"Lublin Hops",
"Magnum Hops",
"Mt. Hood Hops",
"Northdown Hops",
"Northern Brewer Hops",
"Nugget Hops",
"Orion Hops",
"Pacific Hops",
"Pearle Hops",
"Phoenix Hops",
"Pilgrim Hops",
"Pioneer Hops",
"Pride of Ringwood Hops",
"Progress Hops",
"Saaz Hops",
"Santiam Hops",
"Select Spalt Hops",
"Southern Cross Hops",
"Spalter Hops",
"Sterling Hops",
"Sticklebract Hops",
"Strisselspalt Hops",
"Styrian Goldings Hops",
"Sun Hops",
"Super Alpha Hops",
"Target Hops",
"Tettnang Hops",
"Tradition Hops",
"Ultra Hops",
"Vanguard Hops",
"Warrior Hops",
"Whitbread Golding Var (WGV) Hops",
"Willamette Hops",
"Zeus Hops",
"Water"
];